version: '3'
services:
  vue:
    build: .
    ports:
      - "8888:80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx 구성 파일을 마운트
    ports:
      - "80:80"
    depends_on:
      - vue
